ServerTokens Prod
ServerSignature Off

<VirtualHost *:443>

  ServerName localhost

  DocumentRoot /var/www/html/public

  SSLEngine on

  SSLCertificateFile    /etc/ssl/localcerts/selfsigned.crt
  SSLCertificateKeyFile /etc/ssl/localcerts/selfsigned.key

  # TLS 1.2 only
  SSLProtocol -all +TLSv1.2

  # Export-grade cipher suites
  SSLCipherSuite EXPORT:EXPORT40:EXPORT56

  # Server enforces its cipher preference
  SSLHonorCipherOrder on

  <Directory /var/www/html/public>
    AllowOverride All
    Require all granted
  </Directory>

  ErrorLog ${APACHE_LOG_DIR}/error-ssl.log
  CustomLog ${APACHE_LOG_DIR}/access-ssl.log combined

</VirtualHost>